# -*- coding: utf-8 -*-
"""narcissism_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGXYobDjOL3enjjYn1pfOnM3kBR-wqV_
"""

# -*- coding: utf-8 -*-
"""
Interactive Narcissistic Personality Trait Assessment Tool
Designed for educational evaluation and clinical parameter modeling.
"""

class NarcissisticProfile:
    def __init__(self, name: str, level_score: float, spectrum_tier: str):
        self.name = name
        self.assessment_score = level_score  # Total points scored
        self.tier = spectrum_tier            # Low, Moderate, High, or Pathological

        # Dynamically scale psychological attributes (0.0 to 10.0) based on the score
        # Assuming max score from assessment is 15 points
        scale_factor = min(10.0, (level_score / 15.0) * 10)

        self.ego_inflation = round(scale_factor, 1)
        self.need_for_admiration = round(scale_factor, 1)
        self.empathy_level = round(10.0 - (scale_factor * 0.8), 1)  # Empathy decreases as traits rise
        self.narcissistic_supply_reservoir = 5.0

    def display_profile(self):
        """Prints the calculated psychological baseline of the patient."""
        print(f"\n=========================================")
        print(f" PSYCHOLOGICAL PROFILE GENERATED: {self.name}")
        print(f"=========================================")
        print(f"Spectrum Tier:     {self.tier} ({self.assessment_score} points)")
        print(f"Ego Inflation:     {self.ego_inflation}/10")
        print(f"Need for Praise:   {self.need_for_admiration}/10")
        print(f"Empathy Baseline:  {self.empathy_level}/10")
        print(f"=========================================\n")


def run_therapist_assessment() -> NarcissisticProfile:
    print("==================================================")
    print("  CLINICAL PARAMETER INPUT: NARCISSISM SPECTRUM   ")
    print("==================================================")
    print("Rate each indicator from 0 (Not Present) to 3 (Severe/Constant):\n")

    patient_name = input("Enter Patient Identifier / Name: ")

    try:
        # Question 1: Grandiosity
        q1 = float(input("1. Grandiose sense of self-importance (0-3): "))
        # Question 2: Empathy
        q2 = float(input("2. Lack of empathy / unwillingness to recognize others' feelings (0-3): "))
        # Question 3: Entitlement
        q3 = float(input("3. Unreasonable expectations of especially favorable treatment (0-3): "))
        # Question 4: Admiration seeking
        q4 = float(input("4. Excessive need for admiration and validation (0-3): "))
        # Question 5: Exploitative Behavior
        q5 = float(input("5. Interpersonally exploitative (takes advantage of others) (0-3): "))

        # Calculate total score (Max possible: 15)
        total_score = q1 + q2 + q3 + q4 + q5

        # Determine the spectrum classification tier
        if total_score <= 4:
            tier = "Low / Healthy Narcissistic Traits"
        elif total_score <= 8:
            tier = "Moderate / Subclinical Narcissism"
        elif total_score <= 12:
            tier = "High Narcissistic Traits"
        else:
            tier = "Severe / Pathological (High NPD Probability)"

        # Instantiate and return the custom profile object
        return NarcissisticProfile(patient_name, total_score, tier)

    except ValueError:
        print("\n[ERROR] Invalid input. Please enter numbers between 0 and 3.")
        return None

# --- Execution ---
if __name__ == "__main__":
    patient_profile = run_therapist_assessment()
    if patient_profile:
        patient_profile.display_profile()

